// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
)

const template = `// Code generated by generator.go.
// source:
// application.js
// DO NOT EDIT!

package main

// Application Javascript code
var Application = %#v
`

func main() {
	data, err := ioutil.ReadFile("application.js")
	if err != nil {
		panic(err)
	}

	code := fmt.Sprintf(template, data)
	err = ioutil.WriteFile("application.go", []byte(code), 0644)
	if err != nil {
		panic(err)
	}
}
